--DATA DICTIONARY VIEWS: USER TABLES , ALL TABLES , USER_TAB_COLUMNS , USER_CONS_COLUMNS , USER_CONSTRAINT , COMMENT

--DICTIONARY
SELECT * FROM DICTIONARY;

--USER_TABLES
SELECT * FROM USER_TABLES;


--ALL_TABLES
SELECT * FROM ALL_TABLES;

--USER_TAB_COLUMNS
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEPARTMENTS';

--USER_CONS_COLUMNS
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

--user catalog
select * from user_catalog;

--comment
COMMENT ON TABLE EMPLOYEES
IS 'THIS TABLE CONTAINS EMPLOYEES DATA';

select * from user_tab_comments
where table_name = 'EMPLOYEES';

COMMENT ON COLUMN EMPLOYEES.SALARY
IS 'THE SALARY OF EMPLOYEE';

select * from USER_COL_COMMENTS
where table_name = 'EMPLOYEES'
AND COLUMN_NAME = 'SALARY';

