--START WHERE , BETWEEN , IN , LIKE , IS NULL , NOT  , NOT EQUAL ,LOGICAL OPERATORS(AND, OR ,NOT) , ORDER BY , ROWNUM

--WHERE 
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 102;

SELECT EMPLOYEE_ID , FIRST_NAME AS NAME , LAST_NAME AS SURNAME FROM EMPLOYEES WHERE FIRST_NAME = 'John';

SELECT EMPLOYEE_ID , FIRST_NAME  NAME , LAST_NAME  SURNAME FROM EMPLOYEES WHERE HIRE_DATE = '17-OCT-03';

--WHERE WITH ORDER_BY
SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 105 ORDER BY EMPLOYEE_ID;

--BETWEEN
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 101 AND 110;

--BETWEEN WITH ORDER BY 
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000 ORDER BY SALARY;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME BETWEEN 'A' AND 'M' ORDER BY FIRST_NAME;

--IN
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (101 , 102 ,103);

--INSTEAD OF IN
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 101 OR EMPLOYEE_ID = 102 OR EMPLOYEE_ID = 103;


--LIKE
--(FIRST_NAME BEGIN WITH S CHARACTER)
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'S%' ORDER BY FIRST_NAME;

--(s CHARACTER SHOULD BE IN THE FIRST_NAME (BEGIN OR MIDDLE OR END) ) 
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%s%' ORDER BY FIRST_NAME;

--(FIRST_NAME ENDS WITH s CHARACTER) 
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%s' ORDER BY FIRST_NAME;


--IS NULL
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;


--NOT
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID NOT IN (101, 102 ,103);

--NOT WITH LIKE , AND , ORDER BY
SELECT * FROM EMPLOYEES WHERE FIRST_NAME NOT LIKE 'A%' AND FIRST_NAME NOT LIKE 'B%' ORDER BY FIRST_NAME;

-- <>
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID <> 101;


-- !=
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID != 101;

--OR
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 100 OR EMPLOYEE_ID = 101;

--AND
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID > 110 AND SALARY > 12000;


--AND WITH OR
SELECT * FROM EMPLOYEES WHERE (EMPLOYEE_ID = 145 OR EMPLOYEE_ID = 146) AND SALARY > 13300;


--ORDER BY
SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID;

SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME;

SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID DESC;

SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME DESC;

--ORDER BY WITH NUMBER
SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME FROM EMPLOYEES ORDER BY 1; --1 EQUALS TO EMPLOYEE_ID 

SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME FROM EMPLOYEES ORDER BY 2; --2 EQUALS TO FIRST_NAME 

SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME FROM EMPLOYEES ORDER BY 3; --3 EQUALS TO LAST_NAME 

SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME , HIRE_DATE FROM EMPLOYEES ORDER BY HIRE_DATE;

SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME , HIRE_DATE FROM EMPLOYEES ORDER BY HIRE_DATE DESC;

--ORDER BY WITH ALIAS
SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME , HIRE_DATE H FROM EMPLOYEES ORDER BY H;


--ORDER BY WITH NULL VALUES
SELECT EMPLOYEE_ID , FIRST_NAME ,LAST_NAME , COMMISSION_PCT CP FROM EMPLOYEES ORDER BY CP;

--NULLS COMING FIRST WITH ORDER BY DESC
SELECT EMPLOYEE_ID , FIRST_NAME ,LAST_NAME , COMMISSION_PCT CP FROM EMPLOYEES ORDER BY CP DESC;

--NULLS FIRST (ORDER BY WITH ASC BUT NULL VALUES COMING FIRST)
SELECT EMPLOYEE_ID , FIRST_NAME ,LAST_NAME , COMMISSION_PCT CP FROM EMPLOYEES ORDER BY CP NULLS  FIRST;


--ORDER BY ASC AND DESC IN THE SAME EXPRESSION AT THE SAME TIME
SELECT EMPLOYEE_ID , FIRST_NAME NAME , LAST_NAME SURNAME FROM EMPLOYEES ORDER BY NAME ASC , SURNAME DESC;


--ROWNUM
SELECT ROWNUM ,EMPLOYEE_ID , FIRST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 105 ORDER BY EMPLOYEE_ID ;


