--TIME ZONES

SELECT INTERVAL '01-08' YEAR TO MONTH FROM DUAL;  --RESULT : 1 YEAR AND 8 MONTH

SELECT INTERVAL '300' MONTH FROM DUAL; -- RESULT : 25 YEAR 0 MONTH

SELECT INTERVAL '10' YEAR FROM DUAL; --RESULT : 10 YEAR 0 MONTH

SELECT INTERVAL '33 20:20:20' DAY TO SECOND FROM DUAL; --RESULT: 33 DAY  20 HOURS 20 MINUTE 20 SECOND 

SELECT INTERVAL '600' HOUR FROM DUAL; --RESULT : 25 DAY



SELECT SYSDATE , SYSDATE + 10 FROM DUAL;
     
--I WANT TO ADD 2 YEARS 4 MONTH TO SYSDATE 
SELECT SYSDATE , SYSDATE + INTERVAL '02-04' YEAR TO MONTH FROM DUAL;

--AND ALSO WE DO THIS WITH TO_YMINNTERVAL

SELECT SYSDATE , SYSDATE + TO_YMINTERVAL('02-04') FROM DUAL;  

--I WANT TO ADD 10 DAYS AND 5 HOURS TO SYSDATE
SELECT SYSDATE , SYSDATE + TO_DSINTERVAL('10 05:00:00') FROM DUAL;

--LET'S SEE THE RESULT
SELECT TO_CHAR(SYSDATE , 'dd-MM-YYYY hh:mi:ss') ,
TO_CHAR(SYSDATE + TO_DSINTERVAL('10 05:00:00') , 'dd-MM-YYYY hh:mi:ss') FROM DUAL;



--EXTRACT 
SELECT 
EXTRACT (YEAR FROM SYSDATE) "YEAR",
EXTRACT (MONTH FROM SYSDATE) "MONTH",
EXTRACT (DAY FROM SYSDATE) "DAY"
FROM DUAL;



SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME ,
EXTRACT (YEAR FROM HIRE_DATE ) "YEAR",
EXTRACT (MONTH FROM HIRE_DATE ) "MONTH"
FROM EMPLOYEES;



--TIMESTAMP  , TIMEZONE

CREATE TABLE TIME_DATE_STAMP
(
   DATE1 DATE ,
   DATE2 TIMESTAMP,
   DATE3 TIMESTAMP WITH TIME ZONE
   
);


INSERT INTO TIME_DATE_STAMP
VALUES(SYSDATE , CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 

SELECT * FROM time_date_stamp;



--TIMEZONE
SELECT * FROM v$timezone_names;


SELECT * FROM v$timezone_names
WHERE TZNAME = 'Asia/Baku';
        
    
SELECT DBTIMEZONE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT LOCALTIMESTAMP FROM DUAL;


--AND ALSO WE CAN CHANGE TIME ZONE
--LIKE  THIS : ALTER SESSION SET TIME_ZONE = 'America/Chicago';


